stages:
  - build
  - stage

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker system prune -af --volumes
  except: 
    - master  
  only:
    - tags
  when: on_success
  tags:
    - shell-runner
    
stage:
  stage: stage
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_TAG}/g" deployment-stage.yaml
    - kubectl -n stage apply -f deployment-stage.yaml
    - cat deployment-stage.yaml
  when: on_success
  only:
    - tags
  except:
    - master
  tags:
    - shell-runner
    